# Generated by Django 2.2.1 on 2020-09-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='process_state',
            field=models.BooleanField(blank=True, null=True, verbose_name='文章审核'),
        ),
    ]
