# Generated by Django 2.2.1 on 2020-09-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200929_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='标题编号'),
        ),
    ]
