# Generated by Django 2.2.1 on 2020-10-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201008_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='clicked',
            field=models.IntegerField(default=0, null=True, verbose_name='点击数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='comment_count',
            field=models.IntegerField(default=0, null=True, verbose_name='评论数'),
        ),
    ]
