# Generated by Django 2.2.1 on 2020-11-05 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201009_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='account_ID',
        ),
        migrations.AddField(
            model_name='comments',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户website'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='state',
            field=models.BooleanField(blank=True, null=True, verbose_name='评论状态'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
