# Generated by Django 2.2.1 on 2020-11-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comments_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='state',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='评论状态'),
        ),
    ]
