# Generated by Django 2.2.1 on 2019-10-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=64, null=True, verbose_name='链接')),
                ('path', models.CharField(blank=True, max_length=64, null=True, verbose_name='Path')),
                ('component', models.CharField(blank=True, max_length=64, null=True, verbose_name='component')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='名称')),
                ('iconCls', models.CharField(blank=True, max_length=64, null=True, verbose_name='图标')),
                ('keepAlive', models.BooleanField(blank=True, default=None, null=True, verbose_name='')),
                ('requireAuth', models.BooleanField(blank=True, default=None, null=True, verbose_name='')),
                ('parentId', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('enabled', models.BooleanField(blank=True, default=True, null=True, verbose_name='')),
            ],
        ),
    ]
