# Generated by Django 2.2.1 on 2019-09-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmAdminMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(blank=True, verbose_name='上级菜单编号  外键 parent_id=0为顶级菜单  parent_id=menu_id 取出二级菜单')),
                ('nenu_names', models.CharField(blank=True, max_length=64, verbose_name='菜单名称')),
                ('action_code', models.CharField(blank=True, max_length=64, verbose_name='标识码(唯一的 不可重复)  根据标识码来判断是否有权限')),
                ('url', models.CharField(blank=True, max_length=64, verbose_name='菜单的跳转页面')),
                ('is_show', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否显示  1为显示  0不显示')),
                ('is_status', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否显示  1为显示  0不显示')),
                ('menu_order', models.IntegerField(blank=True, default=99, null=True, verbose_name='排序')),
            ],
        ),
        migrations.CreateModel(
            name='SmWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='网站名字')),
                ('site_url', models.CharField(blank=True, max_length=64, null=True, verbose_name='网站的url,暂时没用上')),
            ],
        ),
    ]
