# Generated by Django 2.2.1 on 2020-02-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_nub', models.CharField(blank=True, max_length=256, null=True, verbose_name='轮播编号')),
                ('carousel_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='轮播链接')),
                ('carousel_info', models.CharField(blank=True, max_length=256, null=True, verbose_name='轮播信息')),
                ('carousel_lg', models.CharField(blank=True, max_length=256, null=True, verbose_name='轮播语言')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_nub', models.CharField(blank=True, max_length=256, null=True, verbose_name='产品编号')),
                ('category_info', models.CharField(blank=True, max_length=256, null=True, verbose_name='推荐信息')),
                ('category_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='推荐信息')),
                ('category_img', models.CharField(blank=True, max_length=256, null=True, verbose_name='推荐信息')),
                ('category_time', models.CharField(blank=True, max_length=256, null=True, verbose_name='推荐时间')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_nub', models.CharField(blank=True, max_length=256, null=True, verbose_name='contact编号')),
                ('contact_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='contact链接')),
                ('contact_info', models.CharField(blank=True, max_length=256, null=True, verbose_name='contact信息')),
                ('contact_lg', models.CharField(blank=True, max_length=256, null=True, verbose_name='contact语言')),
            ],
        ),
        migrations.CreateModel(
            name='FlowerImgUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_nub', models.CharField(blank=True, max_length=256, null=True, verbose_name='flower编号')),
                ('flower_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='flower链接')),
                ('flower_info', models.CharField(blank=True, max_length=256, null=True, verbose_name='flower信息')),
                ('flower_lg', models.CharField(blank=True, max_length=256, null=True, verbose_name='flower语言')),
            ],
        ),
        migrations.CreateModel(
            name='FooterListInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_list_nub', models.CharField(blank=True, max_length=256, null=True, verbose_name='footer_list编号')),
                ('footer_list_sort', models.CharField(blank=True, max_length=256, null=True, verbose_name='footer_list排序')),
                ('footer_list_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='footer_list链接')),
                ('footer_list_info', models.CharField(blank=True, max_length=256, null=True, verbose_name='footer_list信息')),
                ('footer_list_lg', models.CharField(blank=True, max_length=256, null=True, verbose_name='footer_list语言')),
            ],
        ),
        migrations.CreateModel(
            name='IndexInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_info', models.CharField(blank=True, max_length=256, null=True, verbose_name='信息名字')),
                ('page_where', models.CharField(blank=True, max_length=256, null=True, verbose_name='信息位置')),
                ('page_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='信息显示 ')),
                ('page_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='信息链接')),
                ('page_lg', models.CharField(blank=True, max_length=256, null=True, verbose_name='信息语言 ')),
            ],
        ),
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_nub', models.CharField(blank=True, max_length=256, null=True, verbose_name='新闻编号')),
                ('news_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='新闻名称')),
                ('news_info', models.CharField(blank=True, max_length=256, null=True, verbose_name='新闻信息')),
                ('news_lg', models.CharField(blank=True, max_length=256, null=True, verbose_name='新闻语言')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_nub', models.CharField(blank=True, max_length=256, null=True, verbose_name='产品编号')),
                ('product_info', models.CharField(blank=True, max_length=256, null=True, verbose_name='推荐信息')),
                ('product_time', models.CharField(blank=True, max_length=256, null=True, verbose_name='推荐时间')),
            ],
        ),
    ]
