# Generated by Django 2.2.1 on 2020-02-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0002_carouseldisplay_categoryrecommendation_contactinfo_flowerimgurl_footerlistinfo_indexinfo_newsinfo_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsinfo',
            name='news_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='新闻URL'),
        ),
    ]
