# Generated by Django 2.2.1 on 2020-02-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0003_newsinfo_news_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_info', models.CharField(blank=True, max_length=256, null=True, verbose_name='信息名字')),
                ('page_where', models.CharField(blank=True, max_length=256, null=True, verbose_name='信息位置')),
                ('page_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='信息链接')),
            ],
        ),
    ]
