# Generated by Django 2.2.1 on 2020-02-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0004_indexurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexurl',
            name='page_url',
        ),
        migrations.AddField(
            model_name='indexurl',
            name='page_lg',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='信息语言 '),
        ),
    ]
