# Generated by Django 2.2.1 on 2020-02-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0005_auto_20200216_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouseldisplay',
            name='carousel_img',
            field=models.ImageField(default='photos/default.png', upload_to='photos/'),
        ),
    ]
