# Generated by Django 2.2.1 on 2020-02-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0006_carouseldisplay_carousel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowerimgurl',
            name='flower_text',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='flower文本'),
        ),
    ]
