# Generated by Django 2.2.1 on 2020-02-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0007_flowerimgurl_flower_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouseldisplay',
            name='carousel_info',
        ),
        migrations.RemoveField(
            model_name='carouseldisplay',
            name='carousel_lg',
        ),
        migrations.RemoveField(
            model_name='categoryrecommendation',
            name='category_info',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='flowerimgurl',
            name='flower_info',
        ),
        migrations.RemoveField(
            model_name='flowerimgurl',
            name='flower_lg',
        ),
        migrations.RemoveField(
            model_name='flowerimgurl',
            name='flower_text',
        ),
        migrations.RemoveField(
            model_name='footerlistinfo',
            name='footer_list_info',
        ),
        migrations.RemoveField(
            model_name='footerlistinfo',
            name='footer_list_lg',
        ),
        migrations.RemoveField(
            model_name='indexinfo',
            name='page_lg',
        ),
        migrations.RemoveField(
            model_name='indexinfo',
            name='page_name',
        ),
        migrations.RemoveField(
            model_name='indexurl',
            name='page_info',
        ),
        migrations.RemoveField(
            model_name='indexurl',
            name='page_lg',
        ),
        migrations.RemoveField(
            model_name='indexurl',
            name='page_where',
        ),
        migrations.RemoveField(
            model_name='newsinfo',
            name='news_info',
        ),
        migrations.RemoveField(
            model_name='newsinfo',
            name='news_lg',
        ),
        migrations.RemoveField(
            model_name='newsinfo',
            name='news_name',
        ),
        migrations.RemoveField(
            model_name='productrecommendation',
            name='product_info',
        ),
        migrations.RemoveField(
            model_name='smadminmenu',
            name='nenu_names',
        ),
        migrations.RemoveField(
            model_name='smwebsite',
            name='site_name',
        ),
        migrations.AddField(
            model_name='carouseldisplay',
            name='carousel_info_en_us',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='carousel_info (英语)'),
        ),
        migrations.AddField(
            model_name='carouseldisplay',
            name='carousel_info_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='carousel_info (España)'),
        ),
        migrations.AddField(
            model_name='carouseldisplay',
            name='carousel_info_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='carousel_info (Le français)'),
        ),
        migrations.AddField(
            model_name='carouseldisplay',
            name='carousel_info_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='carousel_info (Português)'),
        ),
        migrations.AddField(
            model_name='carouseldisplay',
            name='carousel_info_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='carousel_info (中文简体)'),
        ),
        migrations.AddField(
            model_name='carouseldisplay',
            name='carousel_info_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='carousel_info (中文繁体)'),
        ),
        migrations.AddField(
            model_name='categoryrecommendation',
            name='category_info_en_us',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='category_info (英语)'),
        ),
        migrations.AddField(
            model_name='categoryrecommendation',
            name='category_info_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='category_info (España)'),
        ),
        migrations.AddField(
            model_name='categoryrecommendation',
            name='category_info_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='category_info (Le français)'),
        ),
        migrations.AddField(
            model_name='categoryrecommendation',
            name='category_info_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='category_info (Português)'),
        ),
        migrations.AddField(
            model_name='categoryrecommendation',
            name='category_info_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='category_info (中文简体)'),
        ),
        migrations.AddField(
            model_name='categoryrecommendation',
            name='category_info_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='category_info (中文繁体)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='contact_info_en_us',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='contact_info (英语)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='contact_info_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='contact_info (España)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='contact_info_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='contact_info (Le français)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='contact_info_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='contact_info (Português)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='contact_info_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='contact_info (中文简体)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='contact_info_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='contact_info (中文繁体)'),
        ),
        migrations.AddField(
            model_name='flowerimgurl',
            name='flower_img',
            field=models.ImageField(default='photos/default.png', upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='flowerimgurl',
            name='flower_info_en_us',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='flower_info (英语)'),
        ),
        migrations.AddField(
            model_name='flowerimgurl',
            name='flower_info_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='flower_info (España)'),
        ),
        migrations.AddField(
            model_name='flowerimgurl',
            name='flower_info_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='flower_info (Le français)'),
        ),
        migrations.AddField(
            model_name='flowerimgurl',
            name='flower_info_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='flower_info (Português)'),
        ),
        migrations.AddField(
            model_name='flowerimgurl',
            name='flower_info_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='flower_info (中文简体)'),
        ),
        migrations.AddField(
            model_name='flowerimgurl',
            name='flower_info_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='flower_info (中文繁体)'),
        ),
        migrations.AddField(
            model_name='flowerimgurl',
            name='flower_text_en_us',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='flower_text (英语)'),
        ),
        migrations.AddField(
            model_name='flowerimgurl',
            name='flower_text_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='flower_text (España)'),
        ),
        migrations.AddField(
            model_name='flowerimgurl',
            name='flower_text_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='flower_text (Le français)'),
        ),
        migrations.AddField(
            model_name='flowerimgurl',
            name='flower_text_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='flower_text (Português)'),
        ),
        migrations.AddField(
            model_name='flowerimgurl',
            name='flower_text_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='flower_text (中文简体)'),
        ),
        migrations.AddField(
            model_name='flowerimgurl',
            name='flower_text_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='flower_text (中文繁体)'),
        ),
        migrations.AddField(
            model_name='footerlistinfo',
            name='footer_list_info_en_us',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='footer_list_info (英语)'),
        ),
        migrations.AddField(
            model_name='footerlistinfo',
            name='footer_list_info_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='footer_list_info (España)'),
        ),
        migrations.AddField(
            model_name='footerlistinfo',
            name='footer_list_info_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='footer_list_info (Le français)'),
        ),
        migrations.AddField(
            model_name='footerlistinfo',
            name='footer_list_info_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='footer_list_info (Português)'),
        ),
        migrations.AddField(
            model_name='footerlistinfo',
            name='footer_list_info_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='footer_list_info (中文简体)'),
        ),
        migrations.AddField(
            model_name='footerlistinfo',
            name='footer_list_info_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='footer_list_info (中文繁体)'),
        ),
        migrations.AddField(
            model_name='indexinfo',
            name='page_name_en_us',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_name (英语)'),
        ),
        migrations.AddField(
            model_name='indexinfo',
            name='page_name_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_name (España)'),
        ),
        migrations.AddField(
            model_name='indexinfo',
            name='page_name_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_name (Le français)'),
        ),
        migrations.AddField(
            model_name='indexinfo',
            name='page_name_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_name (Português)'),
        ),
        migrations.AddField(
            model_name='indexinfo',
            name='page_name_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_name (中文简体)'),
        ),
        migrations.AddField(
            model_name='indexinfo',
            name='page_name_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_name (中文繁体)'),
        ),
        migrations.AddField(
            model_name='indexurl',
            name='page_info_en_us',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_info (英语)'),
        ),
        migrations.AddField(
            model_name='indexurl',
            name='page_info_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_info (España)'),
        ),
        migrations.AddField(
            model_name='indexurl',
            name='page_info_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_info (Le français)'),
        ),
        migrations.AddField(
            model_name='indexurl',
            name='page_info_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_info (Português)'),
        ),
        migrations.AddField(
            model_name='indexurl',
            name='page_info_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_info (中文简体)'),
        ),
        migrations.AddField(
            model_name='indexurl',
            name='page_info_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_info (中文繁体)'),
        ),
        migrations.AddField(
            model_name='indexurl',
            name='page_where_en_us',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_where (英语)'),
        ),
        migrations.AddField(
            model_name='indexurl',
            name='page_where_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_where (España)'),
        ),
        migrations.AddField(
            model_name='indexurl',
            name='page_where_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_where (Le français)'),
        ),
        migrations.AddField(
            model_name='indexurl',
            name='page_where_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_where (Português)'),
        ),
        migrations.AddField(
            model_name='indexurl',
            name='page_where_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_where (中文简体)'),
        ),
        migrations.AddField(
            model_name='indexurl',
            name='page_where_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_where (中文繁体)'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='news_info_en_us',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='news_info (英语)'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='news_info_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='news_info (España)'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='news_info_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='news_info (Le français)'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='news_info_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='news_info (Português)'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='news_info_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='news_info (中文简体)'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='news_info_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='news_info (中文繁体)'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='news_name_en_us',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='news_name (英语)'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='news_name_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='news_name (España)'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='news_name_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='news_name (Le français)'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='news_name_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='news_name (Português)'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='news_name_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='news_name (中文简体)'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='news_name_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='news_name (中文繁体)'),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='product_info_en_us',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='product_info (英语)'),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='product_info_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='product_info (España)'),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='product_info_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='product_info (Le français)'),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='product_info_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='product_info (Português)'),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='product_info_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='product_info (中文简体)'),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='product_info_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='product_info (中文繁体)'),
        ),
        migrations.AddField(
            model_name='smadminmenu',
            name='nenu_names_en_us',
            field=models.CharField(blank=True, db_tablespace='', max_length=64, verbose_name='nenu_names (英语)'),
        ),
        migrations.AddField(
            model_name='smadminmenu',
            name='nenu_names_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=64, verbose_name='nenu_names (España)'),
        ),
        migrations.AddField(
            model_name='smadminmenu',
            name='nenu_names_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=64, verbose_name='nenu_names (Le français)'),
        ),
        migrations.AddField(
            model_name='smadminmenu',
            name='nenu_names_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=64, verbose_name='nenu_names (Português)'),
        ),
        migrations.AddField(
            model_name='smadminmenu',
            name='nenu_names_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=64, verbose_name='nenu_names (中文简体)'),
        ),
        migrations.AddField(
            model_name='smadminmenu',
            name='nenu_names_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=64, verbose_name='nenu_names (中文繁体)'),
        ),
        migrations.AddField(
            model_name='smwebsite',
            name='site_name_en_us',
            field=models.CharField(blank=True, db_tablespace='', max_length=64, verbose_name='site_name (英语)'),
        ),
        migrations.AddField(
            model_name='smwebsite',
            name='site_name_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=64, verbose_name='site_name (España)'),
        ),
        migrations.AddField(
            model_name='smwebsite',
            name='site_name_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=64, verbose_name='site_name (Le français)'),
        ),
        migrations.AddField(
            model_name='smwebsite',
            name='site_name_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=64, verbose_name='site_name (Português)'),
        ),
        migrations.AddField(
            model_name='smwebsite',
            name='site_name_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=64, verbose_name='site_name (中文简体)'),
        ),
        migrations.AddField(
            model_name='smwebsite',
            name='site_name_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=64, verbose_name='site_name (中文繁体)'),
        ),
        migrations.AlterField(
            model_name='categoryrecommendation',
            name='category_img',
            field=models.ImageField(default='photos/default.png', upload_to='photos/'),
        ),
    ]
