# Generated by Django 2.2.1 on 2020-02-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0010_auto_20200221_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouseldisplay',
            name='carousel_info_en_us',
        ),
        migrations.RemoveField(
            model_name='categoryrecommendation',
            name='category_info_en_us',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='contact_info_en_us',
        ),
        migrations.RemoveField(
            model_name='flowerimgurl',
            name='flower_info_en_us',
        ),
        migrations.RemoveField(
            model_name='flowerimgurl',
            name='flower_text_en_us',
        ),
        migrations.RemoveField(
            model_name='footerlistinfo',
            name='footer_list_info_en_us',
        ),
        migrations.RemoveField(
            model_name='indexinfo',
            name='page_name_en_us',
        ),
        migrations.RemoveField(
            model_name='indexurl',
            name='page_info_en_us',
        ),
        migrations.RemoveField(
            model_name='mediaurl',
            name='page_info_en_us',
        ),
        migrations.RemoveField(
            model_name='newsinfo',
            name='news_info_en_us',
        ),
        migrations.RemoveField(
            model_name='newsinfo',
            name='news_name_en_us',
        ),
        migrations.RemoveField(
            model_name='productrecommendation',
            name='product_info_en_us',
        ),
        migrations.RemoveField(
            model_name='smadminmenu',
            name='nenu_names_en_us',
        ),
        migrations.RemoveField(
            model_name='smwebsite',
            name='site_name_en_us',
        ),
        migrations.AddField(
            model_name='carouseldisplay',
            name='carousel_info_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='carousel_info (English)'),
        ),
        migrations.AddField(
            model_name='categoryrecommendation',
            name='category_info_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='category_info (English)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='contact_info_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='contact_info (English)'),
        ),
        migrations.AddField(
            model_name='flowerimgurl',
            name='flower_info_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='flower_info (English)'),
        ),
        migrations.AddField(
            model_name='flowerimgurl',
            name='flower_text_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='flower_text (English)'),
        ),
        migrations.AddField(
            model_name='footerlistinfo',
            name='footer_list_info_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='footer_list_info (English)'),
        ),
        migrations.AddField(
            model_name='indexinfo',
            name='page_name_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_name (English)'),
        ),
        migrations.AddField(
            model_name='indexurl',
            name='page_info_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_info (English)'),
        ),
        migrations.AddField(
            model_name='mediaurl',
            name='page_info_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='page_info (English)'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='news_info_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='news_info (English)'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='news_name_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='news_name (English)'),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='product_info_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='product_info (English)'),
        ),
        migrations.AddField(
            model_name='smadminmenu',
            name='nenu_names_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=64, verbose_name='nenu_names (English)'),
        ),
        migrations.AddField(
            model_name='smwebsite',
            name='site_name_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=64, verbose_name='site_name (English)'),
        ),
    ]
