# Generated by Django 2.2.1 on 2020-02-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0011_auto_20200227_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='contact_lg',
        ),
    ]
