# Generated by Django 2.2.1 on 2020-03-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0014_auto_20200229_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsinfo',
            name='news_name_en',
        ),
        migrations.RemoveField(
            model_name='newsinfo',
            name='news_name_es',
        ),
        migrations.RemoveField(
            model_name='newsinfo',
            name='news_name_fr',
        ),
        migrations.RemoveField(
            model_name='newsinfo',
            name='news_name_pt',
        ),
        migrations.RemoveField(
            model_name='newsinfo',
            name='news_name_zh_hans',
        ),
        migrations.RemoveField(
            model_name='newsinfo',
            name='news_name_zh_hant',
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='news_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='新闻名称'),
        ),
        migrations.AlterField(
            model_name='newsinfo',
            name='news_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='新闻编号'),
        ),
    ]
