# Generated by Django 2.2.1 on 2020-03-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0015_auto_20200303_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsinfo',
            name='news_nub',
        ),
    ]
