# Generated by Django 2.2.1 on 2020-03-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0016_remove_newsinfo_news_nub'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsinfo',
            name='news_nub',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='新闻编号'),
        ),
    ]
