# Generated by Django 2.2.1 on 2020-03-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0017_newsinfo_news_nub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsinfo',
            name='news_nub',
        ),
    ]
