# Generated by Django 2.2.1 on 2020-09-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0018_remove_newsinfo_news_nub'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnListsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_lists_nub', models.CharField(blank=True, max_length=256, null=True, verbose_name='column_lists_nub')),
                ('column_lists_img', models.ImageField(default='photos/default.png', upload_to='photos/')),
                ('column_lists_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='column_lists_title')),
                ('column_lists_subtitle', models.CharField(blank=True, max_length=256, null=True, verbose_name='column_lists_remarks')),
                ('column_lists_alt', models.CharField(blank=True, max_length=256, null=True, verbose_name='column_lists_alt')),
            ],
        ),
        migrations.CreateModel(
            name='InstaContentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_content_nub', models.CharField(blank=True, max_length=256, null=True, verbose_name='insta_content_nub')),
                ('insta_content_img', models.ImageField(default='photos/default.png', upload_to='photos/')),
                ('insta_content_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='insta_content_url')),
                ('insta_content_alt', models.CharField(blank=True, max_length=256, null=True, verbose_name='insta_content_alt')),
            ],
        ),
    ]
