# Generated by Django 2.2.1 on 2020-09-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0019_columnlistsinfo_instacontentinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnlistsinfo',
            name='column_lists_alt',
        ),
        migrations.RemoveField(
            model_name='columnlistsinfo',
            name='column_lists_subtitle',
        ),
        migrations.RemoveField(
            model_name='columnlistsinfo',
            name='column_lists_title',
        ),
        migrations.RemoveField(
            model_name='instacontentinfo',
            name='insta_content_alt',
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_alt_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_alt (English)'),
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_alt_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_alt (España)'),
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_alt_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_alt (Le français)'),
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_alt_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_alt (Português)'),
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_alt_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_alt (中文简体)'),
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_alt_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_alt (中文繁体)'),
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_subtitle_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_subtitle (English)'),
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_subtitle_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_subtitle (España)'),
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_subtitle_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_subtitle (Le français)'),
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_subtitle_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_subtitle (Português)'),
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_subtitle_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_subtitle (中文简体)'),
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_subtitle_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_subtitle (中文繁体)'),
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_title_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_title (English)'),
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_title_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_title (España)'),
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_title_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_title (Le français)'),
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_title_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_title (Português)'),
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_title_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_title (中文简体)'),
        ),
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_lists_title_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='column_lists_title (中文繁体)'),
        ),
        migrations.AddField(
            model_name='instacontentinfo',
            name='insta_content_alt_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='insta_content_alt (English)'),
        ),
        migrations.AddField(
            model_name='instacontentinfo',
            name='insta_content_alt_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='insta_content_alt (España)'),
        ),
        migrations.AddField(
            model_name='instacontentinfo',
            name='insta_content_alt_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='insta_content_alt (Le français)'),
        ),
        migrations.AddField(
            model_name='instacontentinfo',
            name='insta_content_alt_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='insta_content_alt (Português)'),
        ),
        migrations.AddField(
            model_name='instacontentinfo',
            name='insta_content_alt_zh_hans',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='insta_content_alt (中文简体)'),
        ),
        migrations.AddField(
            model_name='instacontentinfo',
            name='insta_content_alt_zh_hant',
            field=models.CharField(blank=True, db_tablespace='', max_length=256, verbose_name='insta_content_alt (中文繁体)'),
        ),
    ]
