# Generated by Django 2.2.1 on 2020-09-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0020_auto_20200914_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnlistsinfo',
            name='column_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='column_lists_nub'),
        ),
    ]
